<?php

use App\Ai\Agents\EventDraftAgent;
use App\Enums\AiGenerationStatus;
use App\Enums\UserRole;
use App\Jobs\EventGenerationJob;
use App\Models\AiGeneration;
use App\Models\User;
use App\Enums\AiOperation;
use App\Services\Ai\EventCopilotService;
use Illuminate\Http\Client\ConnectionException;
use Illuminate\Support\Facades\Queue;

beforeEach(function () {
    $this->user = User::factory()->create(['role' => UserRole::Organizer]);
    config([
        'ai.event_copilot.enabled' => true,
        'ai.event_copilot.provider' => 'openai',
        'ai.event_copilot.model' => 'gpt-4o-mini',
        'ai.event_copilot.fallback_provider' => null,
        'ai.event_copilot.fallback_model' => null,
    ]);
});

it('casts persisted payloads and removes generations with their user', function () {
    $generation = AiGeneration::factory()
        ->for($this->user)
        ->successful(['title' => 'Generated title'])
        ->create();

    expect($generation->status)->toBe(AiGenerationStatus::Success)
        ->and($generation->inputs)->toBeArray()
        ->and($generation->result)->toBe(['title' => 'Generated title'])
        ->and($generation->user->is($this->user))->toBeTrue();

    $this->user->delete();

    $this->assertModelMissing($generation);
});

it('accepts the request, records the generation, and queues the job', function () {
    Queue::fake();

    $response = $this->actingAs($this->user)->postJson(route('organizer.ai.event-drafts'), [
        'brief' => 'A music concert',
        'tone' => 'professional',
        'language' => 'en',
    ]);

    $response->assertStatus(202)
        ->assertJsonStructure([
            'data' => [
                'generation_id',
                'status',
            ],
        ])
        ->assertJsonPath('data.status', 'processing');

    $generation = AiGeneration::query()
        ->whereBelongsTo($this->user)
        ->where('operation', AiOperation::DRAFT->value)
        ->sole();

    expect($generation->status)->toBe(AiGenerationStatus::Processing)
        ->and($generation->inputs)->toMatchArray([
            'brief' => 'A music concert',
            'tone' => 'professional',
            'language' => 'en',
        ])
        ->and($this->user->aiGenerations()->whereKey($generation->id)->exists())->toBeTrue();

    Queue::assertPushed(EventGenerationJob::class, function ($job) {
        return $job->generation->user_id === $this->user->id
            && $job->generation->operation === AiOperation::DRAFT->value;
    });
});

it('runs the operation and stores the result for polling', function () {
    EventDraftAgent::fake([
        [
            'title' => 'Test Event',
            'description' => 'Test description.',
            'category_id' => null,
            'marketing' => [
                'social_post' => 'Test post',
                'email_subject' => 'Test subject',
                'email_intro' => 'Test intro',
            ],
            'missing_information' => [],
        ],
    ]);

    $response = $this->actingAs($this->user)->postJson(route('organizer.ai.event-drafts'), [
        'brief' => 'A test event',
        'tone' => 'professional',
        'language' => 'en',
    ]);

    $response->assertStatus(202);

    $generationId = $response->json('data.generation_id');

    $this->actingAs($this->user)->getJson(
        route('organizer.ai.generations.status', ['generationId' => $generationId]),
    )
        ->assertOk()
        ->assertJsonPath('data.status', 'success')
        ->assertJsonPath('data.result.title', 'Test Event');
});

it('uses the fallback provider on a transient failure', function () {
    $callCount = 0;

    EventDraftAgent::fake(function () use (&$callCount) {
        $callCount++;

        if ($callCount === 1) {
            throw new ConnectionException('Connection timed out');
        }

        return [
            'title' => 'Fallback Event',
            'description' => 'Generated by fallback.',
            'category_id' => null,
            'marketing' => [
                'social_post' => 'Fallback post',
                'email_subject' => 'Fallback subject',
                'email_intro' => 'Fallback intro',
            ],
            'missing_information' => [],
        ];
    });

    config([
        'ai.event_copilot.fallback_provider' => 'groq',
        'ai.event_copilot.fallback_model' => 'openai/gpt-oss-20b',
    ]);

    Queue::fake();

    $response = $this->actingAs($this->user)->postJson(route('organizer.ai.event-drafts'), [
        'brief' => 'A fallback event',
        'tone' => 'professional',
        'language' => 'en',
    ]);

    $response->assertStatus(202);

    $job = Queue::pushed(EventGenerationJob::class)->first();
    $job->handle(app(EventCopilotService::class));

    $generationId = $response->json('data.generation_id');

    $this->actingAs($this->user)->getJson(
        route('organizer.ai.generations.status', ['generationId' => $generationId]),
    )
        ->assertOk()
        ->assertJsonPath('data.status', 'success')
        ->assertJsonPath('data.result.title', 'Fallback Event');

    expect($callCount)->toBe(2);
});

it('stores an error when the generation fails permanently', function () {
    EventDraftAgent::fake(fn () => throw new RuntimeException('AI service is down'));

    Queue::fake();

    $response = $this->actingAs($this->user)->postJson(route('organizer.ai.event-drafts'), [
        'brief' => 'A test event',
        'tone' => 'professional',
        'language' => 'en',
    ]);

    $response->assertStatus(202);

    $job = Queue::pushed(EventGenerationJob::class)->first();

    try {
        $job->handle(app(EventCopilotService::class));
        $exception = null;
    } catch (Throwable $e) {
        $exception = $e;
    }

    $job->failed($exception);

    $generationId = $response->json('data.generation_id');

    $this->actingAs($this->user)->getJson(
        route('organizer.ai.generations.status', ['generationId' => $generationId]),
    )
        ->assertOk()
        ->assertJsonPath('data.status', 'error')
        ->assertJsonPath('data.result', null)
        ->assertJsonPath('data.error_message', 'The AI assistant is temporarily unavailable. Please try again later.');
});

it('reports processing while the job has not stored a result yet', function () {
    Queue::fake();

    $response = $this->actingAs($this->user)->postJson(route('organizer.ai.event-drafts'), [
        'brief' => 'A test event',
        'tone' => 'professional',
        'language' => 'en',
    ]);

    $response->assertStatus(202);

    $generationId = $response->json('data.generation_id');

    $this->actingAs($this->user)->getJson(
        route('organizer.ai.generations.status', ['generationId' => $generationId]),
    )
        ->assertOk()
        ->assertJsonPath('data.status', 'processing');
});

it('keeps the result available after it has been polled', function () {
    EventDraftAgent::fake([
        [
            'title' => 'Ephemeral Event',
            'description' => 'A description.',
            'category_id' => null,
            'marketing' => [
                'social_post' => 'P',
                'email_subject' => 'S',
                'email_intro' => 'I',
            ],
            'missing_information' => [],
        ],
    ]);

    $response = $this->actingAs($this->user)->postJson(route('organizer.ai.event-drafts'), [
        'brief' => 'An ephemeral event',
        'tone' => 'professional',
        'language' => 'en',
    ]);

    $response->assertStatus(202);

    $generationId = $response->json('data.generation_id');

    $this->actingAs($this->user)->getJson(
        route('organizer.ai.generations.status', ['generationId' => $generationId]),
    )
        ->assertOk()
        ->assertJsonPath('data.status', 'success');

    $this->actingAs($this->user)->getJson(
        route('organizer.ai.generations.status', ['generationId' => $generationId]),
    )
        ->assertOk()
        ->assertJsonPath('data.status', 'success');
});
